markdown: kramdown
highlighter: rouge
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

author: "Li Kaijian"
email: likaijian@cqu.edu.cn  
name: "Li Kaijian"
url: likaijian@cqu.edu.cn  
all_categories: [
["read", "Publication","pub.html"], 
["about", "Research Activity","randt.html"]
]

paginate: 3
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
