markdown: kramdown
highlighter: rouge
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

author: "Haoyuan Zhang"
email: haoyuan.zhang@qmul.ac.uk
name: "Haoyuan Zhang"
url: haoyuanzhang1990.github.io
all_categories: [
["read", "Publication","pub.html"], 
["about", "Research and Teaching","randt.html"]
]

paginate: 3
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
